colour = input("Enter a colour:")
noun = input("Enter plural noun:")
celebrity = input("Enter your favourite celebrity's name:")
print("Roses are"+colour)
print(noun+" are blue")
print("I love "+ celebrity)